Use system protoc. Require protoc at least 3.19 because some corner of DLL hell breaks loading the iterm2 module, saying:
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

But don't bother visiting the url because it says diddly squat about this problem. I'm going to hope that regenerating with 3.19 doesn't break anything for anyone everywhere but ¯\_(ツ)_/¯